<?php

namespace Modules\VCards\Http\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class VCardResource extends JsonResource
{
    public function toArray(Request $request): array
    {
        return [
            'id' => $this->id,
            'listing_id' => $this->listing_id,
            'listing_slug' => $this->listing?->slug,
            'listing_name' => $this->listing?->name,
            'vcard_team_id' => $this->vcard_team_id,
            'type' => $this->type->value,
            'name' => $this->name,
            'slug' => $this->slug,
            'active' => $this->active,
            'search_engine_indexing' => $this->search_engine_indexing ?? true,
            'renew' => $this->renew ?? true,
            'tracking_code' => $this->tracking_code ?? [],
            'paused' => $this->paused ?? false,
            'ai_chat_enabled' => $this->ai_chat_enabled ?? false,
            'design' => $this->design->value,
            'primary_color' => $this->primary_color,
            'shape' => $this->shape ?? 'circle',
            'image_x' => $this->image_x ?? 0,
            'image_y' => $this->image_y ?? 0,
            'font' => $this->font,
            'profile_photo' => $this->profile_photo,
            'hero_background_image' => $this->hero_background_image,
            'background_type' => $this->background_type ?? 'solid',
            'gradient_direction' => $this->gradient_direction ?? '135deg',
            'pattern_key' => $this->pattern_key,
            'hero_image_alpha' => $this->hero_image_alpha ?? 100,
            'body_background_type' => $this->body_background_type ?? 'solid',
            'body_primary_color' => $this->body_primary_color ?? '#ffffff',
            'body_gradient_direction' => $this->body_gradient_direction ?? '135deg',
            'body_pattern_key' => $this->body_pattern_key,
            'latitude' => $this->latitude,
            'longitude' => $this->longitude,
            'address' => $this->address,
            'city' => $this->city,
            'state' => $this->state,
            'country' => $this->country,
            'zip' => $this->zip,
            'logo' => $this->logo,
            'badge' => $this->badge,
            'prefix' => $this->prefix,
            'first_name' => $this->first_name,
            'middle_name' => $this->middle_name,
            'last_name' => $this->last_name,
            'full_name' => $this->full_name,
            'accreditations' => $this->accreditations,
            'preferred_name' => $this->preferred_name,
            'pronouns' => $this->pronouns?->value,
            'title' => $this->title,
            'department' => $this->department,
            'company' => $this->company,
            'headline' => $this->headline,
            'views' => $this->views,
            'public_url' => $this->public_url,
            'qr_code_url' => $this->qr_code_url,
            'team' => $this->whenLoaded('team'),
            'seo_setting' => $this->whenLoaded('seoSetting'),
            'contacts' => $this->relationLoaded('contacts') ? VCardContactResource::collection($this->contacts)->resolve($request) : [],
            'fields' => $this->relationLoaded('fields') ? VCardFieldResource::collection($this->fields)->resolve($request) : [],
            'active_fields' => $this->relationLoaded('activeFields') ? VCardFieldResource::collection($this->activeFields)->resolve($request) : [],
            'sections' => $this->whenLoaded('sections', fn() => $this->sections->pluck('enabled', 'section_key')->toArray(), []),
            'services' => $this->whenLoaded('selectedServices', fn() => $this->selectedServices->map(fn($s) => [
                'id' => $s->service?->id,
                'name' => $s->service?->name,
                'price' => $s->service?->price,
                'duration_minutes' => $s->service?->duration_minutes,
                'description' => $s->service?->description,
            ])->filter()->values(), []),
            'packages' => $this->whenLoaded('selectedPackages', fn() => $this->selectedPackages->map(fn($p) => [
                'id' => $p->package?->id,
                'title' => $p->package?->title,
                'short_description' => $p->package?->short_description,
                'price' => $p->package?->price,
                'promo_price' => $p->package?->promo_price,
            ])->filter()->values(), []),
            'gallery' => $this->whenLoaded('selectedGallery', fn() => $this->selectedGallery?->gallery ? [
                'id' => $this->selectedGallery->gallery->id,
                'name' => $this->selectedGallery->gallery->name,
                'images' => $this->selectedGallery->gallery->images?->map(fn($img) => [
                    'id' => $img->id,
                    'path' => $img->path,
                    'title' => $img->title,
                ])->values(),
            ] : null),
            'products' => $this->whenLoaded('selectedProducts', fn() => $this->selectedProducts->map(fn($p) => [
                'id' => $p->product?->id,
                'name' => $p->product?->name,
                'description' => $p->product?->description,
                'price' => $p->product?->price,
                'image' => $p->product?->image,
            ])->filter()->values(), []),
            'testimonials' => $this->whenLoaded('selectedTestimonials', fn() => $this->selectedTestimonials->map(fn($t) => [
                'id' => $t->review?->id,
                'client_name' => $t->review?->client_name,
                'company' => $t->review?->company,
                'comment' => $t->review?->comment,
                'rating' => $t->review?->rating,
                'google_link' => $t->review?->google_link,
            ])->filter()->values(), []),
            'business_hours' => $this->whenLoaded('businessHours', fn() => $this->businessHours->map(fn($h) => [
                'id' => $h->id,
                'day_of_week' => $h->day_of_week,
                'day_name' => $h->day_name,
                'is_open' => $h->is_open,
                'opening_time' => $h->opening_time,
                'closing_time' => $h->closing_time,
                'lunch_start_time' => $h->lunch_start_time,
                'lunch_end_time' => $h->lunch_end_time,
            ])->values(), []),
            'menu' => $this->whenLoaded('selectedMenuCategories', fn() => $this->selectedMenuCategories->map(fn($sc) => [
                'id' => $sc->category?->id,
                'title' => $sc->category?->title,
                'description' => $sc->category?->description,
                'product_ids' => $sc->product_ids ?? [],
                'products' => $sc->products->map(fn($p) => [
                    'id' => $p->id,
                    'title' => $p->title,
                    'description' => $p->description,
                    'price' => $p->price,
                    'image' => $p->image,
                ])->values(),
            ])->filter()->values(), []),
            'location' => $this->whenLoaded('selectedLocation', fn() => $this->selectedLocation?->location ? [
                'id' => $this->selectedLocation->location->id,
                'name' => $this->selectedLocation->location->name,
                'address_line_1' => $this->selectedLocation->location->address_line_1,
                'address_line_2' => $this->selectedLocation->location->address_line_2,
                'city' => $this->selectedLocation->location->city,
                'state' => $this->selectedLocation->location->state,
                'postal_code' => $this->selectedLocation->location->postal_code,
                'country' => $this->selectedLocation->location->country,
                'phone' => $this->selectedLocation->location->phone,
                'latitude' => $this->selectedLocation->location->latitude,
                'longitude' => $this->selectedLocation->location->longitude,
                'directions_url' => $this->selectedLocation->location->directions_url,
            ] : null),
            'features' => $this->whenLoaded('selectedFeatures', fn() => $this->selectedFeatures->map(fn($f) => [
                'id' => $f->feature?->id,
                'title' => $f->feature?->title,
                'description' => $f->feature?->description,
                'icon' => $f->feature?->icon,
            ])->filter()->values(), []),
            'about' => $this->about,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
        ];
    }
}
